// script/lib/App.svelte
<script lang="ts">
  import svelteLogo from "./assets/svelte.svg";
//   import Counter from "./lib/Counter.svelte";
</script>

<main>
  <div class="flex flex-col">
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer"> 
      <img src="/vite.svg" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer"> 
      <img src={svelteLogo} alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

  <div>
    <!-- <Counter /> -->
  </div>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p>
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

// script/lib/App.vue
<script setup lang="ts">
import HelloWorld from "./components/HelloWorld.vue";
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <!-- <img src="/vite.svg" class="logo" alt="Vite logo" /> -->
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>

  <HelloWorld msg="Vite + Vue" />
</template>
